# Your Bot's config values

market: BTCCLP              # Buda.com market where orders will be placed
reference:
  name: Bitstamp            # Reference exchange to use for price
  market: BTCUSD            # Reference market to use for price
prices:
  buy_multiplier: 0.95      # Price multiplier for buy order, ie: 1.05 is 5% above reference
  sell_multiplier: 1.05     # Price multiplier for sell order, ie: 0.95 is 5% under reference
amounts:
 max_base: 1                #  Max amount on sell order, ie: base is BTC on BTCCLP
 max_quote: 25000000        #  Max amount on buy order, ie: quote is CLP on BTCCLP
