# Your Bot's config values

from:
  currency: 'BTC'    # 3 digits currency code
  address: 'Any'     # 'Any' if fiat or every address
to:
  currency: 'CLP'    # 3 digits currency code
  withdraw: True     # True to withdraw converted amount
  address: 'None'    # 'None' if fiat
